"""framelib: A high-level DataFrame library built on Polars and Narwhals."""

from narwhals import col

from ._columns import (
    Array,
    Boolean,
    Categorical,
    Column,
    Date,
    Datetime,
    Decimal,
    Enum,
    Float32,
    Float64,
    Int8,
    Int16,
    Int32,
    Int64,
    Int128,
    List,
    String,
    Struct,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    UInt128,
)
from ._database import DataBase, DuckFrame, Schema, Table
from ._filehandlers import CSV, Json, NDJson, Parquet, ParquetPartitioned
from ._folder import Folder

__all__ = [
    "CSV",
    "Array",
    "Boolean",
    "Categorical",
    "Column",
    "DataBase",
    "Date",
    "Datetime",
    "Decimal",
    "DuckFrame",
    "Enum",
    "Float32",
    "Float64",
    "Folder",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Int128",
    "Json",
    "List",
    "NDJson",
    "Parquet",
    "ParquetPartitioned",
    "Schema",
    "String",
    "Struct",
    "Table",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "UInt128",
    "col",
]
